name: Build Linux

on:
  workflow_dispatch:

jobs:
  release:
    permissions: write-all
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    env:
      ELECTRON_CACHE: ${{ github.workspace }}/.cache/electron
      ELECTRON_BUILDER_CACHE: ${{ github.workspace }}/.cache/electron-builder
      ADS_URLS: ${{ secrets.ADS_URLS }}
      VK_APP_ID: ${{ secrets.VK_APP_ID }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      API_ENDPOINT_URL: ${{ secrets.API_ENDPOINT_URL }}
      YANDEX_TRACKING_ID: ${{ secrets.YANDEX_TRACKING_ID }}
      STATIC_ENDPOINT_URL: ${{ secrets.STATIC_ENDPOINT_URL }}
      DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
      EXT_API_SERVER: ${{ secrets.EXT_API_SERVER }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-node14-x64-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install multilib / py2.7
        run: sudo apt update && sudo apt -y install g++ build-essential software-properties-common gcc-multilib g++-multilib flatpak && wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz && tar xzf Python-2.7.18.tgz && cd Python-2.7.18 && sudo ./configure --enable-optimizations && sudo make altinstall && sudo rm "/usr/bin/python" && sudo ln -s "/usr/local/bin/python2.7" "/usr/bin/python"

      - name: Cache Electron
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.cache/electron
          key: ${{ runner.os }}-node14-x64-electron-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-electron-cache-

      - name: Cache Electron-Builder
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.cache/electron-builder
          key: ${{ runner.os }}-node14-x64-electron-builder-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-electron-builder-cache-

      - name: Install dependencies
        run: yarn --ignore-platform --ignore-engines

      - name: Run build
        run: npm run release:linux

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: Save artifacts
          if-no-files-found: error
          path: |
            release/*.snap
            release/*.AppImage
            release/linux-arm64-unpacked
            release/linux-unpacked
            release/linux-ia32-unpacked
          retention-days: 5
